### ISSUE TITLE
想知道有没有设置拍照尺寸的参数

### ISSUE THREAD

**Issue by CescMessi** [CKTim/Camera2Record#1]
导入项目后发现拍摄出来的图片都是最大尺寸的，如果需要缩放应当如何修改？另外闪光灯的运作方式似乎和常用的相机不同。感谢！

**Comment by CKTim** [comment]
暂时没有提供，可copyt源码，自行修改
![image](https://user-images.githubusercontent.com/19585452/46925480-962f8500-d05e-11e8-913c-d1014d9527f8.png)
